# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f682db382581d3be1d6460d1a8a1b94f239ab66710303603cc390a44db66f39aaa71ea49a666ea2d8b3f2e79849dca700ab18ebeaa2012c337af83d103b62fa2

test:
  secret_key_base: 1dd5440884e5c045fa4006ea81fa5d4562f3281d9064f47c20448dfb38721a75689fba2224ce4eef05e3840642c0231a18664b562593447fa0fadea2e2048634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
